name: CI & Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  # group: ci-${{ github.ref }}
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js & pnpm
        uses: pnpm/setup@v1
        with:
          version: latest
          runtime: node@24
          cache: true

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Prettier check
        run: pnpm format:check

      - name: ESLint
        run: pnpm lint

      - name: Type check
        run: pnpm exec tsc --noEmit

      - name: Resolve BASE path
        id: base
        run: echo "path=/${GITHUB_REPOSITORY#*/}" >> "$GITHUB_OUTPUT"

      - name: Build
        env:
          #API_URL: ${{ vars.API_URL }}
          #API_KEY: ${{ secrets.API_KEY }}
          BASE_PATH: ${{ steps.base.outputs.path }}
        run: pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./out"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
